<script>
    $(function() {

        var options = {
            columnsSelector: ".column",
            itemTemplateSelector: "#podTemplate",
            itemClasses: "pod",
            onCountColumnLenght: function($column) { //first big pod height compensation
                if ($column.hasClass("column-first") || $column.hasClass("column-second")) {
                    return ($column.height() + $(".first-column-holder .special").outerHeight());
                }
            },
            onAddItem: function(count, $column, item, itemData) { //first big pod height compensation
                if ((count > 3) && (count % 5 === 0)) {
                    return $("<div class=\"pod advert\">Special</div>");
                }
            },
            dataUrl: "/fake-json.php",
            disableAutoscroll: true
        };

        var scrollModel = new ScrollModel({options: options});
        new ScrollView({el: $("#infiniteScrollList"), model: scrollModel, options: options});

    })
</script>

<div id="infiniteScrollList">
    <div class="first-column-holder">
        <div class="special">
            Special content
        </div>
        <div class="column column-first"></div>
        <div class="column column-second"></div>
    </div>
    <div class="column column-third"></div>

    <div class="btn btn-more">Load more</div>
    <div class="state no-more-state">There are no more items</div>
    <div class="state load-state">Loading...</div>

    <script type="text/template" id="podTemplate">
        <h3><%= title %></h3>
        <div class="id"><%= id %></div>
        <div class="desc"><%= desc %></div>
    </script>

</div>

