<script>
    $(function() {
        $(".infinity").summitInfinityScroll({
            url: "/data"
        });
    })
</script>

<div class="infinity infinity-responsive">
    <div class="column column-first"></div>
    <div class="column column-second"></div>
    <div class="column column-third"></div>

    <div class="btn btn-more">Load more</div>
    <div class="state no-more-state">There are no more items</div>
    <div class="state load-state">Loading...</div>

    <script type="text/template" class="pod-prototype">
        <h3><%= title %></h3>
        <div class="id"><%= id %></div>
        <div class="desc"><%= desc %></div>
    </script>

</div>

