<script>
    $(function() {

        var options = {
            columnsSelector: ".column",
            itemTemplateSelector: "#podTemplate",
            itemClasses: "pod",
            onCountLenght: function($column) {
//                console.log("Count length:", $column.attr("class"));
            },
            dataUrl: "/json"
        };

        var scrollModel = new ScrollModel({options: options});
        new ScrollView({el: $("#infiniteScrollList"), model: scrollModel, options: options});

    })
</script>

<div id="infiniteScrollList">
    <div class="column column-first"></div>
    <div class="column column-second"></div>
    <div class="column column-third"></div>

    <div class="btn btn-more">Load more</div>
    <div class="state no-more-state">There are no more items</div>
    <div class="state load-state">Loading...</div>

    <script type="text/template" id="podTemplate">
        <h3><%= title %></h3>
        <div class="id"><%= id %></div>
        <div class="desc"><%= desc %></div>
    </script>

</div>

